name: Server Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Run server tests
        working-directory: server
        env:
          NODE_ENV: test
        run: |
          npm test -- --runInBand --detectOpenHandles --verbose
